# Generated by Django 5.0 on 2025-11-03 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("oura_access_token", models.CharField(blank=True, max_length=500)),
                ("token_created_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AIInsight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("insight_type", models.CharField(max_length=50)),
                ("input_hash", models.CharField(max_length=64)),
                ("explanation", models.TextField(blank=True)),
                ("suggestions", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="insights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "insight_type", "input_hash"],
                        name="api_aiinsig_user_id_923ebd_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OuraMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("readiness_score", models.IntegerField(blank=True, null=True)),
                ("sleep_score", models.IntegerField(blank=True, null=True)),
                ("activity_score", models.IntegerField(blank=True, null=True)),
                ("sleep_duration", models.FloatField(blank=True, null=True)),
                ("deep_sleep", models.FloatField(blank=True, null=True)),
                ("rem_sleep", models.FloatField(blank=True, null=True)),
                ("hrv", models.IntegerField(blank=True, null=True)),
                ("resting_hr", models.IntegerField(blank=True, null=True)),
                ("raw_data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="api_ouramet_user_id_cc4b41_idx"
                    )
                ],
                "unique_together": {("user", "date")},
            },
        ),
    ]
