# Generated by Django 5.0 on 2025-11-03 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ourametric",
            name="active_calories",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ourametric",
            name="bedtime_start",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ourametric",
            name="steps",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
