from django.db import models
from django.contrib.auth.models import User


class OuraMetric(models.Model):
    """Daily health metrics from Oura Ring"""
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='metrics')
    date = models.DateField()
    
    # Main scores generated by Oura 
    readiness_score = models.IntegerField(null=True, blank=True)
    sleep_score = models.IntegerField(null=True, blank=True)
    activity_score = models.IntegerField(null=True, blank=True)
    
    # Sleep details (in hours)
    sleep_duration = models.FloatField(null=True, blank=True)
    deep_sleep = models.FloatField(null=True, blank=True)
    rem_sleep = models.FloatField(null=True, blank=True)
    bedtime_start = models.DateTimeField(null=True, blank=True)  # When you went to bed
    
    # Heart metrics
    hrv = models.IntegerField(null=True, blank=True)
    resting_hr = models.IntegerField(null=True, blank=True)
    
    # Activity metrics
    steps = models.IntegerField(null=True, blank=True)
    active_calories = models.IntegerField(null=True, blank=True)
    
    # raw data returned from Oura API 
    raw_data = models.JSONField(default=dict, blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        unique_together = ['user', 'date']
        ordering = ['-date']
    
    def __str__(self):
        return f"{self.user.username} - {self.date}"


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    oura_access_token = models.CharField(max_length=500, blank=True)
    token_created_at = models.DateTimeField(null=True, blank=True)
    
    def __str__(self):
        return f"{self.user.username}'s profile"


class Workout(models.Model):
    """Stores workout sessions from Oura Ring"""
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='workouts')
    oura_id = models.CharField(max_length=255, unique=True)  # Oura's workout ID
    day = models.DateField()  # Date of workout
    activity = models.CharField(max_length=100)  # e.g., "cycling", "running"
    calories = models.IntegerField(null=True, blank=True)
    intensity = models.CharField(max_length=50, null=True, blank=True)  # "easy", "moderate", "hard"
    start_datetime = models.DateTimeField(null=True, blank=True)
    end_datetime = models.DateTimeField(null=True, blank=True)
    source = models.CharField(max_length=50, null=True, blank=True)  # "manual", "autodetected", etc
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ['-day', '-start_datetime']
    
    def __str__(self):
        return f"{self.user.username} - {self.activity} on {self.day}"
    
    @property
    def duration_minutes(self):
        """Calculate workout duration in minutes"""
        if self.start_datetime and self.end_datetime:
            delta = self.end_datetime - self.start_datetime
            return round(delta.total_seconds() / 60)
        return None


class AIInsight(models.Model):
    """Stores AI-generated insights (summaries, trends, chat replies) """
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='insights')
    insight_type = models.CharField(max_length=50)  # 'coach_summary', 'trend', etc
    explanation = models.TextField(blank=True)
    suggestions = models.JSONField(default=list, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        ordering = ['-created_at']
