from django.db import models
from django.contrib.auth.models import User


class OuraMetric(models.Model):
    """Daily health metrics from Oura Ring"""
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='metrics')
    date = models.DateField()
    
    # Main scores generated by Oura 
    readiness_score = models.IntegerField(null=True, blank=True)
    sleep_score = models.IntegerField(null=True, blank=True)
    activity_score = models.IntegerField(null=True, blank=True)
    
    # Sleep details (in hours)
    sleep_duration = models.FloatField(null=True, blank=True)
    deep_sleep = models.FloatField(null=True, blank=True)
    rem_sleep = models.FloatField(null=True, blank=True)
    
    # Heart metrics
    hrv = models.IntegerField(null=True, blank=True)
    resting_hr = models.IntegerField(null=True, blank=True)
    
    # raw data returned from Oura API 
    raw_data = models.JSONField(default=dict, blank=True)
    
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        unique_together = ['user', 'date']
        ordering = ['-date']
        indexes = [
            models.Index(fields=['user', 'date']),
        ]
    
    def __str__(self):
        return f"{self.user.username} - {self.date}"


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    oura_access_token = models.CharField(max_length=500, blank=True)
    token_created_at = models.DateTimeField(null=True, blank=True)
    
    def __str__(self):
        return f"{self.user.username}'s profile"


class AIInsight(models.Model):
    """Stores AI-generated insights (summaries, trends, chat replies) linked to a user and input hash."""
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='insights')
    insight_type = models.CharField(max_length=50)  # 'coach_summary', 'trend', 'chat'
    input_hash = models.CharField(max_length=64) # Hash of input data for cache invalidation
    explanation = models.TextField(blank=True) # AI output
    suggestions = models.JSONField(default=list, blank=True)
    created_at = models.DateTimeField(auto_now_add=True) # timestamp
    class Meta:
        ordering = ['-created_at']
        indexes = [
            models.Index(fields=['user', 'insight_type', 'input_hash']),
        ]
